version: "3"

networks:
  mqtt:

services:
  mqtt-gateway:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "1883:1883"
      - "8080:8080"

    # restart: unless-stopped
    networks:
      - mqtt
